name: Strapi for Production with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout Current Repo
      #   uses: actions/checkout@v2
      #   with:
      #     path: ./builder

      - name: Checkout Strapi Repo
        uses: actions/checkout@v2
        with:
          repository: strapi/strapi
          # path: ./strapi

      - name: Check Directories
        run: |
          wget https://raw.githubusercontent.com/tpeterson66/strapi-builder/main/Dockerfile
          ls -la
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            --build-arg STRAPI_URL=https://strapi.devopsfu.io \
            -t tpeterson66/strapi:${{ github.run_id }} \
            -t tpeterson66/strapi:latest \
            -f Dockerfile .

