name: Strapi for Production with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v2
        with:
          path: ./builder

      - name: Checkout Strapi Repo
        uses: actions/checkout@v2
        with:
          repository: strapi/strapi
          path: ./strapi

      - name: Check Directories
        run: |
          cp $GITHUB_WORKSPACE/builder/Dockerfile.prod $GITHUB_WORKSPACE/strapi/Dockerfile
          ls
          ls -la strapi
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: strapi/
          file: ./Dockerfile
          tags: tpeterson66/strapi:${{ github.run_id }}, tpeterson66/strapi:latest